### ISSUE TITLE
Fatal: Invalid dataset, file size should be 602112B, but got 1806336B

### ISSUE THREAD

**Issue by gemaizi** [AIWintermuteAI/aXeleRate#18]
Two moth ago I train a classifier model and it works well, but today I retrain the same model using same dataset , get an error:
Fatal: Invalid dataset, file size should be 602112B, but got 1806336B
I dont konw why conver to k210 model get this error, 1806336B is three times of 602112B

**Comment by gemaizi** [comment]
By the way today i use the new github code!

**Comment by gemaizi** [comment]
the detector model works well, only classifier model get this error

**Comment by AIWintermuteAI** [comment]
Yes, recently converter code was updated to support proper data preprocessing. What is the structure of your dataset?

**Comment by gemaizi** [comment]
> Yes, recently converter code was updated to support proper data preprocessing. What is the structure of your dataset?

struct of dataset:
five folders name "annimal", "guitar","flower","house","plane"
each folder contains some  jpg images , the shape(width and height) of each image is different,
the only difference between the detector images and classifier images is that the detector images is the same shape, all are 640*480!

**Comment by AIWintermuteAI** [comment]
Different image size shouldn't present a problem, since it resizes images before calibration automatically to the network input size.
I just checked on my local computer, everything seems to be normal. 
Are you running locally or in Colab? If you're use aXeleRate on local computer, can you run 
https://github.com/AIWintermuteAI/aXeleRate/blob/master/tests_training_and_inference.py
this script and see if there are any errors?

**Comment by gemaizi** [comment]
> Different image size shouldn't present a problem, since it resizes images before calibration automatically to the network input size.
> I just checked on my local computer, everything seems to be normal.
> Are you running locally or in Colab? If you're use aXeleRate on local computer, can you run
> https://github.com/AIWintermuteAI/aXeleRate/blob/master/tests_training_and_inference.py
> this script and see if there are any errors?

i use use aXeleRate on local compute(ubuntu18.04), i will try your script to see what happend, thanks!

**Comment by gemaizi** [comment]
> Different image size shouldn't present a problem, since it resizes images before calibration automatically to the network input size.
> I just checked on my local computer, everything seems to be normal.
> Are you running locally or in Colab? If you're use aXeleRate on local computer, can you run
> https://github.com/AIWintermuteAI/aXeleRate/blob/master/tests_training_and_inference.py
> this script and see if there are any errors?

i run the script and it can generate the kmodel but finally have some error:

> 
1. Import graph...
2. Optimize Pass 1...
3. Optimize Pass 2...
4. Quantize...
  4.1. Add quantization checkpoints...
  4.2. Get activation ranges...
  Plan buffers...
  Run calibration...
  [==================================================] 100% 5.364s
  4.5. Quantize graph...
5. Lowering...
6. Generate code...
  Plan buffers...
  Emit code...
Main memory usage: 109200 B

SUMMARY
INPUTS
0	Input_0	1x3x240x320
OUTPUTS
0	dense_1/Softmax	1x5
0
Folder projects/classifier/2020-07-13_18-00-27/Inference_results is created.
Classifier
Loading pre-trained weights for the whole model:  projects/classifier/2020-07-13_18-00-27/Classifier_best_val_accuracy.h5
(227, 300, 3)
Traceback (most recent call last):
  File "tests_training_and_inference.py", line 127, in <module>
    setup_inference(item,model_path)
  File "/home/mgl/aXeleRate/axelerate/infer.py", line 98, in setup_inference
    cv2.putText(orig_image, "{}:{:.2f}".format(img_class[0], prob[0]), (10,30), font, orig_image.shape[1]/700 , (0, 0, 255), 2, True)
TypeError: Argument 'lineType' must be integer, not bool

**Comment by gemaizi** [comment]
here is my config file:


{
    "model" : {
        "type":                 "Classifier",
        "architecture":         "MobileNet7_5",
        "input_size":           224,
        "fully-connected":      [],
        "labels":               [],
        "dropout" : 		0.5
    },
     "weights" : {
            "full":   				"",
            "backend":   		    "imagenet",
            "save_bottleneck":      false
        
    },
    "train" : {
        "actual_epoch":         1,
        "train_image_folder":   "/home/mgl/aXeleRate/my_datasets/classifier/imgs",
        "train_times":          1,
        "valid_image_folder":   "/home/mgl/aXeleRate/my_datasets/classifier/imgs_validation",
        "valid_times":          1,
        "valid_metric":         "val_accuracy",
        "batch_size":           8,
        "learning_rate":        1e-4,
        "saved_folder":   		"my_classifier",
        "first_trainable_layer": "",
        "augumentation":				true
    },
    "converter" : {
        "type":   				["k210","tflite"]
    }
}

**Comment by AIWintermuteAI** [comment]
Okay, so at least the model is converted properly. The error has something to do with opencv - what version of opencv are you using?
For your original problem, Fatal: Invalid dataset, file size should be 602112B, but got 1806336B --- will you be willing to share your dataset or part of it(that you can confirm causing the problem) in private message? Or openly, if your dataset is not confidential.

**Comment by gemaizi** [comment]
> Okay, so at least the model is converted properly. The error has something to do with opencv - what version of opencv are you using?
> For your original problem, Fatal: Invalid dataset, file size should be 602112B, but got 1806336B --- will you be willing to share your dataset or part of it(that you can confirm causing the problem) in private message? Or openly, if your dataset is not confidential.

opencv version is 4.3.0.36 , what is your email address? i will send you my datasets.

**Comment by gemaizi** [comment]
file is too large(180mb),github can not upload

**Comment by AIWintermuteAI** [comment]
Can you try 4.2.0.34?
dmitrywat@gmail.com - alternatively you can share on google drive

**Comment by gemaizi** [comment]
> Can you try 4.2.0.34?
> [dmitrywat@gmail.com](mailto:dmitrywat@gmail.com) - alternatively you can share on google drive

i will try 4.2.0.34

here is my datasets goole drive link,:
[https://drive.google.com/file/d/1BBYCTtd8-nva5WtM2KheysB3xdhwirWb/view](url)

**Comment by AIWintermuteAI** [comment]
Found the issue, please change 
https://github.com/AIWintermuteAI/aXeleRate/blob/cf365c2ed9f51b39d48f104ebc43c72a0fd697d8/axelerate/networks/common_utils/convert.py#L79
to 
with open(os.path.join(temp_folder, bin_filename), "wb") as f:

Should work fine after that! I'll fix it in the next commit. Also, since you have a lot of images in validation dataset, you can change 
https://github.com/AIWintermuteAI/aXeleRate/blob/cf365c2ed9f51b39d48f104ebc43c72a0fd697d8/axelerate/networks/common_utils/convert.py#L64
to
num_imgs = 200
200 should be enough for proper calibration

**Comment by gemaizi** [comment]
> Found the issue, please change
> https://github.com/AIWintermuteAI/aXeleRate/blob/cf365c2ed9f51b39d48f104ebc43c72a0fd697d8/axelerate/networks/common_utils/convert.py#L80
> 
> 
> to
> with open(os.path.join(temp_folder, bin_filename), "wb") as f:
> Should work fine after that! I'll fix it in the next commit. Also, since you have a lot of images in validation dataset, you can change
> https://github.com/AIWintermuteAI/aXeleRate/blob/cf365c2ed9f51b39d48f104ebc43c72a0fd697d8/axelerate/networks/common_utils/convert.py#L64
> 
> 
> to
> num_imgs = 200
> 200 should be enough for proper calibration

good!! now it works, thanks!!

**Comment by AIWintermuteAI** [comment]
Great!

**Comment by limonJumpWatts** [comment]
@AIWintermuteAI 
I used the updated aXeleRate code(the above modification is already done there) but my object-detection model cannot convert to .kmodel. I used the colab notebook, it can convert to tflite but could not convert to .kmodel and no error is showing.
