### ISSUE TITLE
Colab Notebook not able to convert to kmodel

### ISSUE THREAD

**Issue by nicolaivalenti** [AIWintermuteAI/aXeleRate#21]
With the Colab detector notebook, I'm no longer able to convert the models, I can generate my models and convert to Tflite but they do not convert to kmodel

![3](https://user-images.githubusercontent.com/56894506/87926975-c8b3b080-ca82-11ea-9d9d-e167f0c0901b.PNG)

here is the Colab notebook: https://colab.research.google.com/drive/1eRs-dJdV9ij6RVN4X6rTesuoxrNPi5Ng?usp=sharing

I used this notebook to train a custom detector made with my dataset and it worked well, now I created a new PASCAL VOC dataset with VOTT label tool and after the training, the model is not converted to kmodel no matter how much I try. The folder structure is exactly the same as the old dataset and the training is just fine.

I tried again with the old dataset and it works, I really do not know why, the size of the images are the same, same format, same programs used.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Local or Google Colab/Jupyter Notebook
- If Local: conda or native install/ virtual env?
- If Google Colab: tensorflow version?

**Additional context**

**Comment by nicolaivalenti** [comment]
here is the dataset I'm trying to use
[basta.zip](https://github.com/AIWintermuteAI/aXeleRate/files/4947495/basta.zip)

**Comment by dreamsidae** [comment]
I tried your code, it is in line with what you said! Your situation is very similar to this one!
So I will test according to the solution of that case! The kmodel file can be exported correctly!
You can test it according to its operation!

Sorry I am Chinese, I used google to translate into English, hope you can understand!

https://github.com/AIWintermuteAI/aXeleRate/issues/18
"Fatal: Invalid dataset, file size should be 602112B, but got 1806336B"
======================================================================

我试了你的代码，是符合你说的情况！   你的情况和这一个案子十分的近似！ 
故我按那一个案子的解决方式去测试！ 可以正确转出 kmodel 档案！ 
你可以按其操作去测试一下！ 

抱歉我是中国人，我使用  google 翻译转成英文，希望你看的懂！

**Comment by AIWintermuteAI** [comment]
Sorry, was quite busy last few days - @nicolaivalenti I fixed the bug described in https://github.com/AIWintermuteAI/aXeleRate/issues/18 in the latest commit.
Can you try again and see if it solved your problem?

@dreamsidae I think your English is pretty good :)

**Comment by nicolaivalenti** [comment]
@AIWintermuteAI  @dreamsidae  thank you guys, you are amazing, it is working now!
