### ISSUE TITLE
Object detection Google Colab

### ISSUE THREAD

**Issue by Demet95** [AIWintermuteAI/aXeleRate#25]
Hi, im working on the Google Colab (for object detection ) with a Dataset for car plates. I have two questions : First , how can i know the anchors value in the config cell for this dataset? Second, when i run the training and the validation cells i can't see the plots and i dont know if its a bug.

 I work on Google Colab.
![image](https://user-images.githubusercontent.com/70126477/93690044-d349f080-fa99-11ea-905c-213a107f3da8.png)
![image](https://user-images.githubusercontent.com/70126477/93690051-e492fd00-fa99-11ea-8d55-1696f8e74b2b.png)
![image](https://user-images.githubusercontent.com/70126477/93690053-eeb4fb80-fa99-11ea-804a-c42819d46c18.png)
![image](https://user-images.githubusercontent.com/70126477/93690058-f4aadc80-fa99-11ea-9f22-31031f02bd7b.png)
![image](https://user-images.githubusercontent.com/70126477/93690065-fbd1ea80-fa99-11ea-929c-28f46ce2cd7d.png)

Thanks for the help

**Comment by AIWintermuteAI** [comment]
Hello! Regarding your first question - https://github.com/AIWintermuteAI/aXeleRate/issues/22
Regarding the absence of training graphs - I was able to reproduce the issue. I think there might have been some changes in Colab environment. Let me see how can I restore it.

**Comment by AIWintermuteAI** [comment]
I'll put enhancement tag to this issue. In near future I want to migrate all the code to TF 2.0 and use Tensorboard instead of picture graphs. That will solve the issue with Tkinter/matplotlib.

**Comment by AIWintermuteAI** [comment]
In the latest version tensorboard is used instead of picture training graphs. Closing the issue.
