### ISSUE TITLE
是否支持把没有目标的空背景和标签输入训练？

### ISSUE THREAD

**Issue by wwzh2015** [AIWintermuteAI/aXeleRate#40]
这样可以提高错检率是嘛？让模型更稳定

**Comment by AIWintermuteAI** [comment]
Please use the template. 
And while I do speak and read Mandarin Chinese, my main working language is English.
Kindly re-create the issue and fill in the issue template in English.

https://github.com/AIWintermuteAI/aXeleRate/issues/20

**Comment by wwzh2015** [comment]
OK，If these empty negative sample be trained that is no target of image and just a background image, that relevant xml also no target element.

The aXeleRate network have supported these empty negative sample that can be trained? 

The work can improve AP or PR?
