### ISSUE TITLE
Can the aXeleRate support the format?

### ISSUE THREAD

**Issue by wwzh2015** [AIWintermuteAI/aXeleRate#42]
> emm, I mean motorbike and bike 2 classes objects, but I only annotate label bike for single class object to train(positive sample)。
> 
> I don't want annotate label these voc-xml of motorbike for train(negative samples), but these motorbike and bike look is very similar！
> 
> Usually these bikes and motorbikes are not in the same image of dataset!
> 
> So, I want just add these no annotation label voc-xml of motorbike to train(object element is not exist), that can improve recall rate or AP ?
> 
> voc-xml of motorbike example(a negative sample)：
> 
> ```
> <annotation>
> 	<folder>VOC2007</folder>
> 	<filename>fyb004595.jpg</filename>
> 	<source>
> 		<database>Unknown</database>
> 	</source>
> 	<size>
> 		<width>600</width>
> 		<height>775</height>
> 		<depth>3</depth>
> 	</size>
> 	<segmented>0</segmented>
> </annotation>
> ```

The VOC API have supported the format of XML.

**Comment by AIWintermuteAI** [comment]
Please stop creating multiple issues! You already created 3. This is not how Github works.

I'll reply to you in https://github.com/AIWintermuteAI/aXeleRate/issues/41
