### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 35 column 2 (char 1325)

### ISSUE THREAD

**Issue by wwzh2015** [AIWintermuteAI/aXeleRate#44]
What happend？

 # Note that this exception is used from _json
    def __init__(self, msg, doc, pos):
        lineno = doc.count('\n', 0, pos) + 1
        colno = pos - doc.rfind('\n', 0, pos)
        errmsg = "%s: line %d column %d (char %d)" % (msg,lineno,colno,pos)
        ValueError.__init__(self, errmsg)
        self.msg = msg
        self.doc = doc
        self.pos = pos
        self.lineno = lineno
        self.colno = colno

**Comment by AIWintermuteAI** [comment]
https://github.com/AIWintermuteAI/aXeleRate/issues/20

**Comment by wwzh2015** [comment]
Sometime trainning happend that tips:"json.decoder.JSONDecodeError: Expecting ',' delimiter: line 35 column 2 (char 1325) ",]
tensorflow 1.15.4.

**Comment by wwzh2015** [comment]
Sometime trainning happend that tips:"json.decoder.JSONDecodeError: Expecting ',' delimiter: line 35 column 2 (char 1325) ",]
tensorflow 1.15.4.

**Comment by wwzh2015** [comment]
Traceback (most recent call last):
  File "axelerate/train.py", line 188, in <module>
    setup_training(config_file=args.config)
  File "axelerate/train.py", line 160, in setup_training
    config = json.loads(config_buffer.read())
  File "C:\ProgramData\Anaconda3\envs\ax210\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\envs\ax210\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\envs\ax210\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 35 column 2 (char 1325)

**Comment by wwzh2015** [comment]
class JSONDecodeError(ValueError):
    """Subclass of ValueError with the following additional properties:

    msg: The unformatted error message
    doc: The JSON document being parsed
    pos: The start index of doc where parsing failed
    lineno: The line corresponding to pos
    colno: The column corresponding to pos

    """
    # Note that this exception is used from _json
    def __init__(self, msg, doc, pos):
        lineno = doc.count('\n', 0, pos) + 1
        colno = pos - doc.rfind('\n', 0, pos)
        errmsg = "%s: line %d column %d (char %d)" % (msg,lineno,colno,pos)
        ValueError.__init__(self, errmsg)
        self.msg = msg
        self.doc = doc
        self.pos = pos
        self.lineno = lineno
        self.colno = colno

    def __reduce__(self):
        return self.__class__, (self.msg, self.doc, self.pos)

**Comment by wwzh2015** [comment]
sorry，nothing problem
