### ISSUE TITLE
Support for custom input_size no work in kmodel

### ISSUE THREAD

**Issue by formatcom** [AIWintermuteAI/aXeleRate#50]
Support for custom input_size no work.

It only supports input_size 224, with **input_size 240 it returns error**

**Comment by formatcom** [comment]
> Please, use the template, thank you!

https://github.com/AIWintermuteAI/aXeleRate/blob/master/configs/person_detector.json#L5

if the input_size is changed to a different value it does not work in kmodel v3 / v4

**Comment by AIWintermuteAI** [comment]
https://github.com/AIWintermuteAI/aXeleRate/issues/20

**Comment by AIWintermuteAI** [comment]
Okay, well, I'm not a mind-reader, nor do I want to be one. I really wanted to see the error message and normal description of the problem. 
I think what you're trying to say is that you have an error during conversion stage, if setting input_size to 240. I don't think it is the case - unless your model is too big to begin with and the error you're seeing relates to memory requirements of K210 converter.
I cannot help any further without log/concise description of the problem.

Feel free to comment if you're ready to provide logs/error description according to the template. Closing the issue for now.
