### ISSUE TITLE
[unstable branch] validation frequency adding to config.json

### ISSUE THREAD

**Issue by yangtuo250** [AIWintermuteAI/aXeleRate#51]
**Is your feature request related to a problem? Please describe.**
Validation per epoch will slow down training process severely when validation dataset is large.

**Describe the solution you'd like**
Validation frequency can be modified in config.json

**Comment by AIWintermuteAI** [comment]
I merged your PR. The feature might be useful, I'll see if I propagate it to the master branch in the future.
