### ISSUE TITLE
[unstable branch] yolo training quantize or not can be switched by config.json

### ISSUE THREAD

**Issue by yangtuo250** [AIWintermuteAI/aXeleRate#52]
**Is your feature request related to a problem? Please describe.**
in axelerate/training.py custom training is commented out and quantize training is a default choice.

**Describe the solution you'd like**
Add a boolean "quantize" param in config.json and switch training mode for yolo in training.py.

**Comment by AIWintermuteAI** [comment]
That's because this branch is called "unstable"... It is used for QAT and pruning experiments.
