### ISSUE TITLE
[unstable branch] yolo k210 converter failed while nncase compile and YOLOv3 convert incorrectly

### ISSUE THREAD

**Issue by yangtuo250** [AIWintermuteAI/aXeleRate#53]
**Describe the bug**
When converting YOLOv3 with k210 target:
1. dynamic input shape(batch) lead to upsampling layer convert to several layers in tflite model, thus first layer of Upsampling2D converted tflite layer "shape" does not supported by nncase;
2. YOLOv3 with 2 outputs is converted to only 1 output in tflite

**Expected behavior**
1. fix input layer by adding batch=1
2. treat YOLOv2 and YOLOv3 separately while tflite convert

**Environment (please complete the following information):**
- Local conda environment, tensorflow-gpu==2.4.1

**Comment by AIWintermuteAI** [comment]
Thanks for the tip about setting input shape! I merged your PR to unstable branch. Will need to do some changes afterwards.
