### ISSUE TITLE
Problems with the config - How to train more epochs

### ISSUE THREAD

**Issue by enrique-torres** [AIWintermuteAI/aXeleRate#7]
I seem to be having issues with the config, as said in a previous issue. Is there a way to train more epochs?

**Comment by AIWintermuteAI** [comment]
Yes, of course, it's the "actual epoch" line in the config:
        "train" : {
            "actual_epoch":         5,
Do you think the name is confusing?

**Comment by enrique-torres** [comment]
Yes, I feel like the name is a little bit confusing. Maybe something like number_epochs would make more sense. Thank you for everything, with more epochs I am managing to recognize things.
